version: '3.9'

services:
  # CleoAI API Server
  cleoai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
    depends_on:
      - redis
      - mongo
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    command: python main.py api --host 0.0.0.0 --port 8000

  # Redis for short-term memory cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # MongoDB for archival storage
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cleoai_memory
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb

  # Optional: PostgreSQL (if not using Supabase cloud)
  # postgres:
  #   image: postgres:16-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=cleoai
  #     - POSTGRES_PASSWORD=cleoai_password
  #     - POSTGRES_DB=cleoai_memory
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Optional: Supabase local stack
  # Uncomment to run Supabase locally instead of cloud
  # supabase-db:
  #   image: supabase/postgres:15.1.0.117
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=your-super-secret-password
  #   volumes:
  #     - supabase_db_data:/var/lib/postgresql/data

volumes:
  redis_data:
  mongo_data:
  mongo_config:
  # postgres_data:
  # supabase_db_data:

networks:
  default:
    name: cleoai_network