apiVersion: v1
kind: Namespace
metadata:
  name: cleoai
  labels:
    app: cleoai
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: cleoai-quota
  namespace: cleoai
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    limits.cpu: "200"
    limits.memory: "400Gi"
    persistentvolumeclaims: "10"
    services: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cleoai-limit-range
  namespace: cleoai
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    type: Container