apiVersion: v2
name: cleoai
description: A Helm chart for CleoAI - Advanced AI Assistant Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/cleoai/cleoai
sources:
  - https://github.com/cleoai/cleoai
maintainers:
  - name: CleoAI Team
    email: team@cleoai.com
icon: https://cleoai.com/logo.png
keywords:
  - ai
  - assistant
  - llm
  - machine-learning
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: 13.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 19.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
annotations:
  category: AI
  licenses: Apache-2.0